apiVersion: apps/v1
kind: Deployment
metadata:
  name: po
spec:
  replicas: 1
  selector:
    matchLabels:
      app: po
  template:
    metadata:
      labels:
        app: po
    spec:
      containers:
      - name: po
        image: po:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
        - name: POSTGRES_HOST
          value: postgresql
        - name: POSTGRES_DB
          value: postgres_db
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: postgres
        - name: HARBOR_URL
          value: "harbor_url"
        livenessProbe:
          httpGet:
            path: /po/healthz
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 20
          failureThreshold: 1
          timeoutSeconds: 5
---