apiVersion: v1
kind: Service
metadata:
  name: po-service
spec:
  selector:
    app: po   # Selector to match the pods of your Python app deployment
  ports:
    - protocol: TCP
      port: 80         # Port on the service
      targetPort: 8000 # Port your Python app is listening on
      nodePort: 30000  # Choose a port number within the range 30000-32767
  type: NodePort